spring:
  application:
    name: LinguaLearn # From application.properties
firebase:
  project:
    id: llm-lingualearn # 기존 firebase.project.id
  service:
    account:
      path: llm-lingualearn-firebase-adminsdk-fbsvc-730ed32982.json # 기존 firebase.service.account.path